name: goal-control-server

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432' 
    enviroment:
     -  POSTGRES_USER=docker
     -  POSTGRES_PASSWORD=docker
     -  POSTGRES_DB=goalsControl